# Generated by Django 3.1.6 on 2021-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210504_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_user_profile',
            name='analysed',
            field=models.IntegerField(default=0),
        ),
    ]
