# Generated by Django 3.1.6 on 2021-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_instagram_user_profile_analysed'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram_user_medias',
            name='media_suare_url',
            field=models.TextField(blank=True),
        ),
    ]
